version: "3.7"
services:
  mole-api:
    container_name: mole-api
    restart: always
    image: mole-api:latest
    environment:
      - PORT=8080
      - CONFIG_LOCATION=.env
    ports:
      - "8080:8080"
  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=Testing1234!
      - POSTGRES_DB=testdb
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-data:
    name: database-data
