version: "3.7"
services:
  mole-api:
    container_name: mole-api
    restart: always
    image: mole-api:latest
    environment:
      - PORT=8080
      - CONFIG_LOCATION=.env
    volumes:
      - /home/node/node_modules
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=Testing1234!
      - POSTGRES_DB=testdb
    volumes:
      - mole-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mole-postgres:
    name: mole-postgres
