apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
  name: mole-metrics
  namespace: lens-metrics
spec:
  tls:
    - hosts:
        - mole-metrics.ere.io
      secretName: mole-metrics-tls
  rules:
    - host: mole-metrics.ere.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 80
